### ISSUE TITLE
UIImagePickerController代理方法不执行

### ISSUE THREAD

**Issue by RoshanDev** [chenqihui/IMFiveApp#2]
现在在项目中UIImagePickerController的代理方法不执行，求助攻。

_imagePicker = [[UIImagePickerController alloc] init];
 _imagePicker.delegate = self;
NSLog(@"delegate1 = %@",[_imagePicker.delegate class]);
[self presentViewController:self.imagePicker animated:YES completion:^{
        NSLog(@"delegate2 = %@",[_imagePicker.delegate class]);
    }];

打印出来的是下面的
2014-11-10 14:48:35.340 SOWOClient[10041:60b] delegate1 = SWChatViewController
2014-11-10 14:48:35.881 SOWOClient[10041:60b] delegate2 = PUUIAlbumListViewController

正常的应该两个都是SWChatViewController

**Comment by Jeswang** [comment]
好大一个坑，多谢提前把坑踩了 @pibao2013
