### ISSUE TITLE
IMFiveApp框架及其坑爹的一个bug

### ISSUE THREAD

**Issue by jcxc** [chenqihui/IMFiveApp#4]
您好，你这个项目写得很棒，只不过有一个很严重的bug。
你的这个框架调用系统相机会完全失效，不知道是什么原因，检查了很多了，查了很多资料，实在不知道问题出现在哪里，还请你帮忙看下。
调用相机打印如下：Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.

**Comment by chenqihui** [comment]
你重新下载一份，最新的，我试过可以，不过我也上传了测试的，在左边点击头像那里。这个bug应该是比较久以前第三方库造成的。
